name: 发布流程

on:
  push:
    tags:
      - v**

jobs:
  build:
    strategy:
      matrix:
        include:
          - source: machoke
            target: linux-machoke
            os: ubuntu-latest
          - source: machoke.exe
            target: windows-machoke.exe
            os: windows-latest
          - source: machoke
            target: apple-machoke
            os: macos-latest

    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-rust-static-library
        working-directory: xglib
        run: cargo build --release
      - name: setup qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          target: desktop
      - name: build application
        run: cmake -B build/release && cmake --build build/release
      - name: rename target
        run: mv build/release/{{ matrix.source }} build/release/{{ matrix.target }}
      - name: upload to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/release/${{ matrix.target}}"
