name: 发布流程

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-rust-static-library
        working-directory: xglib
        run: cargo build --release
      - name: setup qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          target: desktop
      - name: build application
        run: cmake -B build/release && cmake --build build/release
      - name: upload to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: build/release/machoke
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: v0.0.1
